apiVersion: v1
kind: Service
metadata:
  name: giropops
  namespace: default
  labels:
    app: giropops
    run: nginx
    track: stable
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app: giropops
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32222
    protocol: TCP
  - name: prometheus
    port: 32111
    targetPort: 32111
    nodePort: 32111
    protocol: TCP
  sessionAffinity: None

