- name: Garantir quantidade correta de WORKERS
  amazon.aws.ec2_instance:
    name: "{{ cluster_name }}-worker"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image }}"
    security_group: "{{ sec_group_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    region: "{{ region }}"
    profile: "{{ profile }}"
    wait: true

    exact_count: "{{ worker_count }}"
    filters:
      "tag:Role": worker
      "tag:Environment": "{{ environment }}"

    tags:
      Name: "{{ cluster_name }}-worker"
      Role: worker
      Environment: "{{ environment }}"

