---
# defaults file for install-monit-tools
prometheus_repo_name: prometheus-community
prometheus_repo_url: https://prometheus-community.github.io/helm-charts

prometheus_release_name: prometheus
prometheus_namespace: monitoring

prometheus_values: ""
